### ISSUE TITLE
Lacks a lot of files?

### ISSUE THREAD

**Issue by starFelix** [johnno1962/InjectionApp#33]
I had cloned this project , but I found that there lost a lot of files such as "DiskTreeAppDelegate""XprobeSwift.swift". Can you upload the full project?

**Comment by johnno1962** [comment]
It mentions in the readme the you need to clone a few other projects and then there is still one file missingI’m too ashamed of to check in. Why do you need to build from source? By the way there is a new version of injection on the way https://github.com/johnno1962/SwiftPython/blob/master/SwiftPython.playground/Contents.swift you may want to try. I’ve yet to update the readme which taks about eval() but in fact it turned out to be a very solid version of injection. I’d give that a try.

**Comment by starFelix** [comment]
I want to build it by myself for learning how it works. I try to use it in my project, but it didn't work. I want to figure out what's the problem and try to resolve them.

**Comment by johnno1962** [comment]
please read the readme.

**Comment by starFelix** [comment]
I have **read** the readme and I had cloned the projects that you have listed. But I found that the project still lacks a lot of files. I have tried to remove the laced file from project and builed it. But It can't patch successful. 
Or can you resolve the stuck problem which will happen if the injected project was very large and have many subprojects.

**Comment by johnno1962** [comment]
What files are missing?

**Comment by johnno1962** [comment]
I’m sorry I gave you the wrong URL before. The new version of Injection which I’d recommend is https://github.com/johnno1962/InjectionIII. The documentation is not complete just yet.

**Comment by starFelix** [comment]
Thanks for the url you have given. Did injectionIII only support Swift? I try to load the bundle, but I got a error said that `Library not loaded: @rpath/libswiftCore.dylib`.

**Comment by johnno1962** [comment]
Thanks! Objective-C should be supported but there was a problem with the “rpath” for Objective-C projects on iOS. I’ve pushed a minor tweak that should get you up and running.
